<?php
/* @var Codilar\HelloWorld\Block\Hello $block */
?>
<div data-bind="scope: 'knockout-tutorial'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "knockout-tutorial": {
                        "component": "Codilar_HelloWorld/js/viewModel",
                        "template" : "Codilar_HelloWorld/template"
                    }
                }
            }
        }
    }
</script>