<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   <div class="container">
    <div class="row m-3">
        <div class="col-md-12">
        <table class="data table table-order-items  table-striped">
       
        <thead>
        <tr>
            <th ><?php echo __('ID') ?></th>
            <th><?php echo __('Name') ?></th>
            <th><?php echo __('Password') ?></th>

            <th><?php echo __('Email') ?></th>
   
            <th><?php echo __('Created At') ?> </th>

            <th><?php echo __('Updated At') ?> </th>
        </tr>
        </thead>

        <tbody>
        <?php foreach (  $block->getCollection() as $item): ?>
        <tr>
            <td>
            <?php echo $item->getUser_id(); ?>
            </td>
            <td >
            <?php echo $item->getUsername(); ?>
            </td>
            <td >
            <?php echo $item->getPassword(); ?>
            </td>
            <td>
            <?php echo $item->getEmail(); ?>
            </td>
            
            <td>
            <?php echo $item->getcreated_at();?>
            </td>
            <td>
            <?php echo $item->getupdated_at();?>
            </td>
         
            
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
        </div>
    </div>
   </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>